language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
